---
language: ruby
rvm:
  - 3.0.1

notifications:
  email:
    on_success: never

os: linux

services:
  - postgresql

cache:
  bundler: true

before_install:
  - gem install bundler:2.2.17

install:
  - bundle install

before_script:
  - rails db:drop
  - rails db:create
  - rails db:schema:load

script:
  - bundle exec rspec
  - bundle exec rubocop
