---
language: ruby
rvm:
  - 3.0.1

notifications:
  email:
    on_success: never

os: linux

cache:
  bundler: true

before_install:
  - gem install bundler:2.2.17

install:
  - bundle install

script:
  - bundle exec rubocop
